### Import Libraries

In [16]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,StandardScaler
from scipy.stats import zscore
import statsmodels.api  as sm
from sklearn.model_selection import train_test_split,cross_val_score,KFold
from sklearn.linear_model import LinearRegression,LogisticRegression
from sklearn.svm import SVR
from sklearn import metrics
import warnings
warnings.filterwarnings('ignore')
sns.set(rc={'figure.figsize':(14,7)})

In [3]:
filename = 'pima-indians-diabetes.data'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
data=pd.read_csv(filename, names=names)

In [5]:
data.head()

preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

In [6]:
data.tail()

preg  plas  pres  skin  test  mass   pedi  age  class
763    10   101    76    48   180  32.9  0.171   63      0
764     2   122    70    27     0  36.8  0.340   27      0
765     5   121    72    23   112  26.2  0.245   30      0
766     1   126    60     0     0  30.1  0.349   47      1
767     1    93    70    31     0  30.4  0.315   23      0

In [7]:
data.sample()

preg  plas  pres  skin  test  mass   pedi  age  class
407     0   101    62     0     0  21.9  0.336   25      0

In [8]:
data.dtypes

preg       int64
plas       int64
pres       int64
skin       int64
test       int64
mass     float64
pedi     float64
age        int64
class      int64
dtype: object

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   preg    768 non-null    int64  
 1   plas    768 non-null    int64  
 2   pres    768 non-null    int64  
 3   skin    768 non-null    int64  
 4   test    768 non-null    int64  
 5   mass    768 non-null    float64
 6   pedi    768 non-null    float64
 7   age     768 non-null    int64  
 8   class   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [10]:
data.shape

(768, 9)

In [12]:
y=data[['class']]
x=data.iloc[:,:-1]

In [15]:
x_train,x_test,y_trian,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

In [23]:
log=LogisticRegression()
cv=KFold(n_splits=5)
result=cross_val_score(log,x,y,cv=cv)
print('Accuracy score :',result.mean()*100,' and the standard deviation: ',result.std()*100)

Accuracy score : 77.35166793990324  and the standard deviation:  3.4787393425522124


# LOOCV

In [26]:
from sklearn.model_selection import LeaveOneOut

In [29]:
data=np.array([10,20,30,40,50,60,70,80,90,100])
loocv=LeaveOneOut()
for train,test in loocv.split(data):
    print(train,test)

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]
